apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mambg-tmm-team
  description: MAMBG TMM Team
spec:
  type: team
  profile:
    displayName: MAMBG TMM Team
    email: mapbu-tmm@vmware.com
    picture: https://avatars.dicebear.com/api/identicon/mapbu-tmm@vmware.com.svg?background=%23fff&margin=25
  parent: mambg-org
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ben-user
spec:
  profile:
    displayName: Ben Wilcock
    email: ben@blah.cloud
    picture: https://avatars.githubusercontent.com/u/5331092?v=4
  memberOf: [mambg-tmm-team]
# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: alana-user
# spec:
#   profile:
#     displayName: Alana App
#     email: alana@blah.cloud
#     picture: https://api.dicebear.com/5.x/avataaars/svg?seed=alana@blah.cloud
#   memberOf: [mambg-tmm-team]